FROM node:20
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Generate Prisma client inside the container (required for Linux runtime)
RUN npx prisma generate

EXPOSE 3000
CMD ["npm","start"]
